### ISSUE TITLE
Inconsistent result with :Farr

### ISSUE THREAD

**Issue by sQVe** [brooth/far.vim#82]
Hey :wave:,

I'm getting a inconsistent result between `:Far` and `:Farr`. I have the following settings set: 

```text
let g:far#source = 'rg'
```
When executing `:Far foo bar **/*.*` it correctly ignores all files listed in my `.gitignore` file. When I use `:Farr` and input the same options/settings it does not. In my case, working with a Node.js project, it completely freezes when using `:Farr` due to it traversing the whole `node_modules` file structure - which is quite large...

Just ping me if I need to provide any further information! :pray:

**Comment by hyliang96** [comment]
I also found this bug for `rg` in `far.vim`. This is caused by the `--glob` option of `rg`. In my fork, I implemented ignore-rules for far.vim searching, which may help you with the issue.

As mentioned in `man rg`, `rg --glob=xxxx` doesn't obey the `.gitignore`.

 >      -g, --glob GLOB ...
 >          Include or exclude files and directories for searching that match the given
 >          glob. This always overrides any other ignore logic. Multiple glob flags may
 >          be used. Globbing rules match .gitignore globs. Precede a glob with a ! to
 >          exclude it.

note that "**This always overrides any other ignore logic**".

## A small verification
 
First, I make a dir `test_dir` for test

```
test_dir/
    .gitignore
    ignore, unignore, .ignore, .unignore
    bin/
          .gitignore
           ignore, unignore, .ignore, .unignore
```

with the commands below:     

```bash
mkdir test_dir
cd test_dir

git init
echo 'testi' > ignore
echo 'testi' > unignore
echo 'testi' > .ignore
echo 'testi' > .unignore

echo '/ignore' >> .gitignore
echo '/.ignore' >> .gitignore

mkdir bin
cd bin
echo 'testi' > ignore
echo 'testi' > unignore
echo 'testi' > .ignore
echo 'testi' > .unignore

echo '/ignore' >> .gitignore
echo '/.ignore' >> .gitignore

cd ..
git add -A .
git commit -m 'gitignore test'
```

Then, in `test_dir/`,  I run `rg testi` without `--glob` option, and the result is as you expected. `rg` doesn't match the files in `.gitignore`.

```
unignore
1:testi

bin/unignore
1:testi
```

However, when running `rg testi --glob=**/*`, and the result shows that `rg` doesn't  obey`.gitignore`.

```
.unignore
1:testi

.ignore
1:testi

ignore
1:testi

bin/.unignore
1:testi

unignore
1:testi

bin/.ignore
1:testi

bin/ignore
1:testi

bin/unignore
1:testi
```

## my test on far.vim 

 On `3c6a6a1`, I run the following command under 'test_dir' in vim.

![ScreenShot 2020-02-12 03 59 17](https://user-images.githubusercontent.com/30200581/74273833-0aaa2f00-4d4c-11ea-9164-23bb211e9f6b.png)

And the result is shown below, which matches the verification above but is different from your result.

![image](https://user-images.githubusercontent.com/30200581/74273924-30cfcf00-4d4c-11ea-86a2-8bf43ebe666f.png)
![image](https://user-images.githubusercontent.com/30200581/74275669-4b577780-4d4f-11ea-97f1-e8458faac8f5.png)

## How to solve this

Since `rg` doesn't support glob and ignore together, I implemented glob and ignore with python `pathlib`. The code is in my fork https://github.com/hyliang96/far.vim/.  You can create one or more `farignore` files just as `.gitignore`. Far.vim will obey `farignore`.  This solution is available for ag/rg/ack, but not vimgrep.  See `doc/far.txt` for details. After testing it, I'll hand in a pull request.

Due to the difference between the glob format  for `pathlib` and `.gitignore`,  for now (`afd9697` in my fork) it can not always parse `.gitignore` correctly.  I'll appreciate if you have any ideas to solve the problem.

**Comment by sQVe** [comment]
@hyliang96 I still find it strange that `Far` and `Farr` give me different results.

**Comment by sQVe** [comment]
Found `Only 'vimgrep' supports |:Farr| and |:Farf|.` in the docs now.

I think this should be made clearer. Using vimgrep in a Node.js project is problematic as it hangs Vim.

Closing.

**Comment by hyliang96** [comment]
In version (e4068a6) , `vimgrep` `ag(nvim)` `rg(nvim)` `ack(nvim)` all support `:Farr` and `:Farf`, and the sentence `Only 'vimgrep' supports |:Farr| and |:Farf|. ` is now removed from  `doc/far.txt`. Please update your far.vim and try again. Be free to let me know if `Far` and `Farr` still give you different results in this version.

By the way, in this version `ag(nvim)` `rg(nvim)` `ack(nvim)`  use the same glob format, while `vimgrep` uses its own glob format. `doc/far.txt` gives detailed exsamples about it.

**Comment by sQVe** [comment]
@hyliang96 The result is now consistent between the two commands for me. Cheers for the quick fix :+1:

**Comment by sQVe** [comment]
@hyliang96 Is there a way to consistently, with a setting or something, to exclude `.gitignore` or at least the `node_modules` directory? I tried playing around with the `ignore_files` setting but I was unsuccessful.

**Comment by stsewd** [comment]
I wanted to ignore a similar directory while using rg. Looks like `ignore_files` expect each rule to be separated by a new line. I just added the directory to https://github.com/brooth/far.vim/blob/master/farignore

Would be great if `ignore_files` could be compatible with the format from `.gitignore`

**Comment by stsewd** [comment]
Found the real problem, with `node_modules` far ignores only _files_ named `node_modules`, if you want to ignore a dir, you need to use `node_modules/`

I made a PR to make far compatible with gitignore, where `node_modules` ignores both, files and directories named `node_modules` https://github.com/brooth/far.vim/pulls
